#!/usr/bin/env node
## Node alpine
FROM node:16.18.0-buster AS build

## Configurando variáveis de Ambiente
ENV APP_HOME=/usr/environment-node

## diretorio de trabalho
WORKDIR "$APP_HOME"

LABEL description="environment-node"

LABEL org.opencontainers.image.name="environment-node"
LABEL org.opencontainers.image.authors="laxederbr@gmail.com"
LABEL org.opencontainers.image.hostname="environment-node"

LABEL com.docker.volume.name='environment-node'
LABEL com.docker.network.bridge.name='environment-node'

## Arquivos de iniciacao para o node
COPY package*.json ./

## install dependences com permissoes root
RUN npm install npm@9.1.2
RUN npm install -g nodemon
RUN npm install -g prisma
RUN npm install

## Copia projeto
COPY . .

## porta de acesso
EXPOSE 3000

## diretorio padrao
VOLUME /usr/environment-node

## start do ambiente
CMD ["npm", "run", "dev"]
