#!/usr/bin/env node
## Node alpine
FROM node:16.18.0-buster AS build

## Configurando variáveis de Ambiente
ENV APP_HOME=/usr/environment-node

## diretorio de trabalho
WORKDIR "$APP_HOME"

LABEL description="environment-node"

LABEL org.opencontainers.image.name="environment-node"
LABEL org.opencontainers.image.authors="laxederbr@gmail.com"
LABEL org.opencontainers.image.hostname="environment-node"

LABEL com.docker.volume.name='environment-node'
LABEL com.docker.network.bridge.name='environment-node'

## Arquivos de iniciacao para o node
COPY package*.json ./

## install dependences com permissoes root
RUN npm install npm@9.1.2
RUN npm install -g nodemon
RUN npm install -g yarn --force
RUN npm install --force

## Copia projeto
COPY . .

# ## alterar permissões para o formato linux
# RUN find ./prisma -type f -print0 | xargs -0 sed -i 's/\r$//'
# RUN find ./src -type f -print0 | xargs -0 sed -i 's/\r$//'
# RUN find ./prisma -type d -print0 | xargs -0 chmod 755  
# RUN find ./src -type d -print0 | xargs -0 chmod 755  
# RUN find ./prisma -type f -print0 | xargs -0 chmod 644
# RUN find ./src -type f -print0 | xargs -0 chmod 644
# RUN cd ./prisma && chmod -R +x *.js
# RUN cd ./src && chmod -R +x *.js
# RUN chmod -R +x ./app.js

# RUN chmod -R +zx *.ts

## porta de acesso
EXPOSE 3000

## diretorio padrao
VOLUME /usr/environment-node

## start do ambiente
CMD ["npm", "run", "dev"]
